# Generated by Django 3.2.8 on 2021-10-15 17:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc



class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='file',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 17, 59, 53, 908866, tzinfo=utc)),
        ),
    ]
